#include "imx6ull.h"
#include "clk.h"

void clk_enable(void)
{
    // CCM->CCGR0 = 0XFFFFFFFF;
    // CCM->CCGR1 = 0XFFFFFFFF;
    // CCM->CCGR2 = 0XFFFFFFFF;
    // CCM->CCGR3 = 0XFFFFFFFF;
    // CCM->CCGR4 = 0XFFFFFFFF;
    // CCM->CCGR5 = 0XFFFFFFFF;
    // CCM->CCGR6 = 0XFFFFFFFF;
    CCM_CCGR0 = 0XFFFFFFFF;
    CCM_CCGR1 = 0XFFFFFFFF;
    CCM_CCGR2 = 0XFFFFFFFF;
    CCM_CCGR3 = 0XFFFFFFFF;
    CCM_CCGR4 = 0XFFFFFFFF;
    CCM_CCGR5 = 0XFFFFFFFF;
    CCM_CCGR6 = 0XFFFFFFFF;
}
